
import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, any>) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  ar: {
    // Navigation
    dashboard: 'لوحة التحكم',
    quran: 'القرآن',
    hadith: 'الحديث',
    duas: 'الأدعية',
    adhkar: 'الأذكار',
    dhikr: 'الذكر',
    habits: 'العادات',
    discover: 'اكتشف',
    saved: 'المحفوظات',
    progress: 'التقدم',
    reminders: 'التذكيرات',
    settings: 'الإعدادات',
    calendar: 'التقويم',
    books: 'الكتب',
    home: 'الرئيسية',
    explore: 'استكشف',
    notes: 'الملاحظات',
    bookmarks: 'المفضلة',
    analytics: 'التحليلات',
    
    // Challenge/Community related
    'join-challenge': 'انضم للتحدي',
    'other-challenges': 'تحديات أخرى',
    'daily-charity': 'الصدقة اليومية',
    'complete-quran-ramadan': 'أكمل القرآن في رمضان',
    'night-prayer-challenge': 'تحدي صلاة الليل',
    'days': 'أيام',
    
    // Calendar and Events
    'hijri-calendar': 'التقويم الهجري',
    'upcoming-events': 'الأحداث القادمة',
    'islamic-new-year': 'رأس السنة الهجرية',
    'day-of-ashura': 'يوم عاشوراء',
    'blessed-event-approaching': 'الحدث المبارك يقترب قريباً',
    'dhul-hijjah': 'ذو الحجة',
    'saturday': 'السبت',
    'gregorian': 'الميلادي',
    
    // Spiritual Wellness
    'spiritual-wellness-tracker': 'متتبع الصحة الروحية',
    'how-spiritual-state-today': 'كيف حالتك الروحية اليوم؟',
    'good': 'جيد',
    
    // Progress Analytics
    'progress-analytics': 'تحليل التقدم',
    'weekly-activity': 'النشاط الأسبوعي',
    'activity-distribution': 'توزيع النشاط',
    'recent-achievements': 'الإنجازات الأخيرة',
    'week': 'أسبوع',
    'month': 'شهر',
    'year': 'سنة',
    'minutes-read': 'دقائق القراءة',
    'surahs-read': 'السور المقروءة',
    'dhikr-count': 'عدد الذكر',
    'reading-min': 'القراءة (دقيقة)',
    'keep-up-consistency': 'حافظ على الاستمرارية',
    'chapter-complete': 'فصل مكتمل',
    'finished-al-fatihah': 'انتهيت من الفاتحة',
    'daily-goal-met': 'تم تحقيق الهدف اليومي',
    '100-dhikr-today': '+١٠٠ ذكر اليوم',
    '7-day-streak': 'سلسلة ٧ أيام!',
    
    // Main Header
    'app-name': 'رفيق الدين',
    'search-all': 'البحث في الكل',
    
    // Tab Navigation - Additional missing keys
    'saved': 'المحفوظات',
    'progress': 'التقدم',
    'reminders': 'التذكيرات',
    
    // Common
    save: 'حفظ',
    cancel: 'إلغاء',
    add: 'إضافة',
    edit: 'تعديل',
    delete: 'حذف',
    search: 'بحث',
    loading: 'جارٍ التحميل...',
    complete: 'مكتمل',
    incomplete: 'غير مكتمل',
    yes: 'نعم',
    no: 'لا',
    ok: 'موافق',
    done: 'تم',
    continue: 'متابعة',
    back: 'رجوع',
    next: 'التالي',
    previous: 'السابق',
    close: 'إغلاق',
    view: 'عرض',
    all: 'الكل',
    of: 'من',
    for: 'لـ',
    translation: 'الترجمة',
    transliteration: 'النطق',
    reference: 'المرجع',
    error: 'خطأ',
    'show-less': 'عرض أقل',
    'show-translation': 'عرض الترجمة',
    'click-to-copy': 'انقر للنسخ',
    travel: 'السفر',
    protection: 'الحماية',
    
    // Prayer Time Tracker
    'prayer-time-tracker': 'متتبع أوقات الصلاة',
    'todays-prayers': 'صلوات اليوم',
    'prayers-remaining': 'صلوات متبقية',
    'mark-complete': 'تحديد كمكتمل',
    
    // Daily Islamic Goals
    'daily-islamic-goals': 'الأهداف الإسلامية اليومية',
    'progress-colon': 'التقدم:',
    'complete-5-daily-prayers': 'أكمل الصلوات الخمس',
    'perform-obligatory-prayers': 'أدي جميع الصلوات الواجبة في الوقت',
    'read-1-page-of-quran': 'اقرأ صفحة واحدة من القرآن',
    'daily-quran-recitation': 'تلاوة القرآن اليومية',
    'morning-evening-adhkar': 'أذكار الصباح والمساء',
    'recite-morning-evening': 'تلاوة أذكار الصباح والمساء',
    'give-charity-sadaqah': 'تصدق (الصدقة)',
    'any-form-charity': 'أي شكل من أشكال الصدقة، حتى الابتسامة',
    'seek-forgiveness-istighfar': 'اطلب المغفرة (الاستغفار)',
    'say-astaghfirullah-100-times': 'قل "أستغفر الله" ١٠٠ مرة',
    'all-goals-completed': 'تم إنجاز جميع الأهداف!',
    'may-allah-accept-efforts': 'تقبل الله منك',
    'add-custom-goal': 'إضافة هدف مخصص',
    
    // Personal Dashboard
    'good-morning': 'صباح الخير',
    'good-afternoon': 'مساء الخير',
    'good-evening': 'مساء الخير',
    'continue-spiritual-journey': 'تابع رحلتك الروحية',
    'day-streak': 'أيام متتالية',
    'total-dhikr': 'إجمالي الذكر',
    'sessions': 'جلسات',
    'goals-met': 'أهداف محققة',
    'todays-goals': 'أهداف اليوم',
    'morning-prayers': 'صلاة الصباح',
    '100-dhikr': '١٠٠ ذكر',
    '15-min-reading': '١٥ دقيقة قراءة',
    'evening-prayers': 'صلاة المساء',
    'weekly-progress': 'التقدم الأسبوعي',
    'great-progress-week': 'تقدم رائع هذا الأسبوع! أنت في المسار الصحيح لتحقيق أهدافك الروحية.',
    'recent-activity': 'النشاط الأخير',
    'last-activity': 'آخر نشاط:',
    'hours-ago': 'منذ ساعتين',
    'read-surah-al-fatihah': 'قراءة سورة الفاتحة',
    
    // Daily Progress
    'daily-progress': 'التقدم اليومي',
    'tasks-completed': 'المهام المكتملة',
    'task-completed': 'تم إنجاز المهمة! ✅',
    'marked-as-complete': 'تم تحديدها كمكتملة',
    'all-tasks-completed': 'تم إنجاز جميع المهام! 🎉',
    'mashallah-completed-tasks': 'ماشاء الله! لقد أكملت جميع المهام اليومية.',
    'progress-reset': 'تم إعادة تعيين التقدم',
    'daily-progress-reset': 'تم إعادة تعيين التقدم اليومي',
    'reset-todays-progress': 'إعادة تعيين تقدم اليوم',
    'morning-dua': 'دعاء الصباح',
    'recite-morning-supplications': 'تلاوة أدعية الصباح',
    'quran-reading': 'قراءة القرآن',
    'read-one-page-quran': 'اقرأ صفحة واحدة على الأقل من القرآن',
    'dhikr-100x': 'ذكر ١٠٠ مرة',
    'complete-100-dhikr': 'أكمل ١٠٠ ذكر',
    'evening-dua': 'دعاء المساء',
    'recite-evening-supplications': 'تلاوة أدعية المساء',
    'istighfar': 'الاستغفار',
    'seek-forgiveness-33-times': 'اطلب المغفرة ٣٣ مرة',
    
    // Settings
    'customize-journey': 'خصص رحلتك الروحية',
    location: 'الموقع',
    'current-location': 'الموقع الحالي',
    'update-location': 'تحديث الموقع',
    notifications: 'الإشعارات',
    'prayer-notifications': 'إشعارات الصلاة',
    'prayer-notifications-desc': 'احصل على إشعارات أوقات الصلاة',
    'adhan-sound': 'صوت الأذان',
    'adhan-sound-desc': 'تشغيل الأذان لأوقات الصلاة',
    'general-notifications': 'الإشعارات العامة',
    'general-notifications-desc': 'تحديثات التطبيق والتذكيرات',
    appearance: 'المظهر',
    'dark-mode': 'الوضع المظلم',
    'dark-mode-desc': 'تبديل المظهر المظلم',
    language: 'اللغة',
    'language-desc': 'تغيير لغة التطبيق',
    'about-app': 'حول رفيق الدين',
    version: 'الإصدار',
    'app-description': 'رفيقك للممارسات الإسلامية والنمو الروحي',
    
    // Languages
    arabic: 'العربية',
    english: 'English',
    
    // Prayer times
    fajr: 'الفجر',
    dhuhr: 'الظهر',
    asr: 'العصر',
    maghrib: 'المغرب',
    isha: 'العشاء',
    
    // Islamic content
    'islamic-quote-day': 'اقتباس إسلامي لليوم',
    points: 'نقاط',
    'complete-daily-prayers': 'أكمل الصلوات الخمس',
    'read-page-quran': 'اقرأ صفحة من القرآن',
    
    // Dream Journal
    'islamic-dream-journal': 'يومية الأحلام الإسلامية',
    'add-dream': 'إضافة حلم',
    'describe-dream': 'صف حلمك:',
    'dream-placeholder': 'حلمت أن...',
    'save-dream': 'حفظ الحلم',
    'islamic-perspective': 'المنظور الإسلامي للأحلام',
    'dream-guidance': 'قال النبي (ص): "الرؤيا الصالحة من الله، والحلم من الشيطان." سجل أحلامك واطلب تفسيرها من خلال المعرفة الإسلامية.',
    'dream-added': 'تم إضافة الحلم',
    'dream-recorded': 'تم تسجيل حلمك في يوميتك.',
    dream: 'الحلم:',
    reflection: 'التأمل:',
    'no-dreams': 'لم يتم تسجيل أحلام بعد. ابدأ يومية أحلامك الروحية!',
    'sample-dream-mosque-light': 'رأيت نفسي أصلي في مسجد جميل بنور ذهبي',
    'sample-dream-interpretation': 'قد يشير هذا إلى النمو الروحي والهداية الإلهية. النور في الأحلام غالباً ما يمثل المعرفة والبر.',
    'reflect-dream-islamic-teachings': 'تأمل في هذا الحلم في ضوء التعاليم الإسلامية. فكر في طلب الإرشاد من مصادر معرفية موثوقة.',
    personal: 'شخصي',
    light: 'نور',
    mosque: 'مسجد',
    prayer: 'صلاة',
    positive: 'إيجابي',
    negative: 'سلبي',
    neutral: 'محايد',
    
    // Charity Tracker
    'charity-impact-tracker': 'متتبع أثر الصدقة',
    'record-donation': 'تسجيل تبرع جديد',
    'amount': 'المبلغ ($)',
    'cause-purpose': 'السبب/الغرض',
    'record-donation-btn': 'تسجيل التبرع',
    'monthly-goal': 'الهدف الشهري',
    'goal-achieved': '🎉 تم تحقيق الهدف! بارك الله فيك.',
    'remaining-goal': '% متبقي للوصول إلى هدفك',
    'people-helped': 'الأشخاص المساعدون',
    'acts-kindness': 'أعمال الخير',
    'this-month': 'هذا الشهر',
    'total-donated': 'إجمالي التبرعات',
    'recent-donations': 'التبرعات الأخيرة',
    'charity-quote': '"ظل المؤمن يوم القيامة صدقته." - النبي محمد (ص)',
    'donation-recorded': 'تم تسجيل التبرع! 🌟',
    'food-for-orphans': 'طعام للأيتام',
    'local-islamic-center': 'المركز الإسلامي المحلي',
    'water-wells': 'آبار المياه',
    'islamic-relief': 'الإغاثة الإسلامية',
    'personal-charity': 'صدقة شخصية',
    'has-been-added-charity-tracker': 'تم إضافته إلى متتبع الصدقة',
    
    // Quranic Word Learning
    'quranic-word-learning': 'تعلم الكلمات القرآنية',
    words: 'كلمات',
    'reveal-meaning': 'كشف المعنى',
    'mark-learned': 'اعتبر كمتعلم',
    learned: '✅ متعلم',
    remaining: 'المتبقي',
    'word-learned': 'تم تعلم الكلمة! 🎉',
    example: 'مثال:',
    'lord-master-sustainer': 'الرب، السيد، المعيل',
    'lord-of-all-worlds': 'رب العالمين',
    'most-gracious': 'الأكثر رحمة',
    'most-gracious-merciful': 'الأكثر رحمة، الأكثر رأفة',
    'establish-prayer': 'أقيموا الصلاة',
    'obligatory-charity': 'الصدقة الواجبة',
    'give-zakah': 'آتوا الزكاة',
    praise: 'الحمد',
    'praise-be-allah': 'الحمد لله',
    'youve-learned': 'لقد تعلمت',
    
    // Spiritual Journal
    'spiritual-journal': 'يومية روحية',
    'new-entry': 'مدخل جديد',
    'search-journal': 'البحث في اليومية...',
    'todays-reflection-prompt': 'موجه التأمل اليوم',
    'entry-title': 'عنوان المدخل...',
    'write-reflections': 'اكتب تأملاتك الروحية هنا...',
    'mood': 'المزاج',
    'tags': 'الوسوم',
    'add-tag': 'إضافة وسم...',
    'save-entry': 'حفظ المدخل',
    'no-journal-entries': 'لا توجد مدخلات في اليومية بعد',
    'start-spiritual-journaling': 'ابدأ رحلة اليومية الروحية!',
    'incomplete-entry': 'مدخل غير مكتمل',
    'add-title-content': 'يرجى إضافة عنوان ومحتوى لمدخل يوميتك.',
    'entry-saved': 'تم حفظ المدخل',
    'reflection-saved': 'تم حفظ تأملك الروحي في يوميتك.',
    'grateful': 'ممتن',
    'peaceful': 'مطمئن',
    'hopeful': 'مليء بالأمل',
    'reflective': 'متأمل',
    'seeking': 'طالب للهداية',
    'current-prompt': 'المحث الحالي:',
    
    // Habit Builder
    'islamic-habit-builder': 'بناء العادات الإسلامية',
    'overall-level': 'المستوى العام',
    'habits-completed-today': 'عادات مكتملة اليوم',
    'habit-completed': 'تم إنجاز العادة!',
    'streak-days': 'أيام متتالية',
    'level-up': 'ارتقاء في المستوى!',
    'reached-level': 'وصل إلى المستوى',
    'add-new-islamic-habit': 'إضافة عادة إسلامية جديدة',
    'most-beloved-deeds': '"أحب الأعمال إلى الله أدومها وإن قل." - النبي محمد (ص)',
    'recent-achievement': 'إنجاز حديث',
    'consistent-reader': 'قارئ مثابر - قرأ القرآن لمدة ١٠ أيام متتالية!',
    'morning-adhkar': 'أذكار الصباح',
    'recite-morning-remembrance': 'تلاوة أذكار الصباح',
    'read-quran': 'قراءة القرآن',
    'read-one-page-daily': 'اقرأ صفحة واحدة على الأقل من القرآن يومياً',
    'make-dua-parents': 'ادع للوالدين',
    'remember-parents-prayers': 'تذكر الوالدين في الصلوات اليومية',
    worship: 'العبادة',
    knowledge: 'المعرفة',
    character: 'الأخلاق',
    health: 'الصحة',
    
    // Surah translations and names
    'quran-karim': 'القرآن الكريم',
    'popular-surahs': 'السور الشائعة',
    'the-opening': 'الفاتحة',
    'the-sincerity': 'الإخلاص',
    'the-daybreak': 'الفلق',
    mankind: 'الناس',
    'the-cow': 'البقرة',
    'the-cave': 'الكهف',
    'the-beneficent': 'الرحمن',
    'the-sovereignty': 'الملك',
    surah: 'سورة',
    'back-to-surahs': 'العودة إلى السور',
    'toggle-translation': 'تبديل الترجمة',
    'verse-copied-clipboard': 'تم نسخ الآية إلى الحافظة',
    'full-surah-copied-clipboard': 'تم نسخ السورة كاملة إلى الحافظة',
    'recently-read': 'قُرئت مؤخراً',
    
    // Duas Section
    'daily-duas': 'الأدعية اليومية',
    'daily-duas-supplications': 'الأدعية اليومية (التضرعات)',
    'search-duas-placeholder': 'البحث في الأدعية أو النطق أو الترجمة...',
    'morning-dua-translation': 'أصبحنا وأصبح الملك لله، والحمد لله',
    'evening-dua-translation': 'أمسينا وأمسى الملك لله، والحمد لله',
    'food-drink': 'الطعام والشراب',
    'before-eating': 'قبل الطعام',
    'after-eating': 'بعد الطعام',
    'before-eating-translation': 'باسم الله.',
    'after-eating-translation': 'الحمد لله الذي أطعمني هذا ورزقنيه من غير حول مني ولا قوة',
    'when-starting-journey': 'عند بدء الرحلة',
    'travel-dua-translation': 'سبحان الذي سخر لنا هذا وما كنا له مقرنين وإنا إلى ربنا لمنقلبون',
    'ayat-kursi': 'آية الكرسي',
    'ayat-kursi-translation': 'الله لا إله إلا هو الحي القيوم',
    'copy-arabic-text': 'نسخ النص العربي',
    'no-duas-found': 'لم يتم العثور على أدعية تطابق بحثك.',
    
    // Bookmarks
    'added-to-bookmarks': 'تم إضافته إلى المحفوظات',
    'removed-from-bookmarks': 'تم إزالته من المحفوظات',
    'already-bookmarked': 'محفوظ مسبقاً',
    'item-already-bookmarked': 'هذا العنصر محفوظ مسبقاً في مفضلتك.',
    'item-saved-bookmarks': '{title} تم حفظه في مفضلتك.',
    'dua-saved-bookmarks': '{title} تم حفظه في مفضلتك.',
    'dua-removed-bookmarks': '{title} تم إزالته من مفضلتك.',
    'dua-arabic-copied': 'تم نسخ النص العربي لـ {title}',
    
    // Toast messages
    'surah-loaded': 'تم تحميل السورة',
    'surah-ready-reading': 'سورة {name} جاهزة للقراءة.',
    'failed-load-surah': 'فشل في تحميل السورة. يرجى المحاولة مرة أخرى.',
    'found-result': 'تم العثور على النتيجة',
    'navigated-to': 'تم الانتقال إلى {title}',
    
    // Quran verse translations
    'bismillah-translation': 'بسم الله الرحمن الرحيم',
    'alhamdulillah-translation': 'الحمد لله رب العالمين',
    'rahman-rahim-translation': 'الرحمن الرحيم',
    'malik-yawm-translation': 'مالك يوم الدين',
    'iyyaka-nabudu-translation': 'إياك نعبد وإياك نستعين',
    'ihdina-sirat-translation': 'اهدنا الصراط المستقيم',
    'sirat-alladhina-translation': 'صراط الذين أنعمت عليهم غير المغضوب عليهم ولا الضالين',
    'qul-huwa-allah-translation': 'قل هو الله أحد',
    'allah-samad-translation': 'الله الصمد',
    'lam-yalid-translation': 'لم يلد ولم يولد',
    'walam-yakun-translation': 'ولم يكن له كفواً أحد',
    'qul-auzu-birabb-falaq': 'قل أعوذ برب الفلق',
    'min-sharri-ma-khalaq': 'من شر ما خلق',
    'min-sharri-ghasiq': 'ومن شر غاسق إذا وقب',
    'min-sharri-naffathat': 'ومن شر النفاثات في العقد',
    'min-sharri-hasid': 'ومن شر حاسد إذا حسد',
    'qul-auzu-birabb-nas': 'قل أعوذ برب الناس',
    'maliki-nas': 'ملك الناس',
    'ilahi-nas': 'إله الناس',
    'min-sharri-waswas': 'من شر الوسواس الخناس',
    'alladhi-yuwaswis': 'الذي يوسوس في صدور الناس',
    'min-jinnati-wanas': 'من الجنة والناس',
    
    // Bottom navigation
    'quran-tab': 'القرآن',
    'explore-tab': 'استكشف',
    'home-tab': 'الرئيسية',
    'duas-tab': 'الأدعية',
    'notes-tab': 'الملاحظات',
  },
  en: {
    // Navigation
    dashboard: 'Dashboard',
    quran: 'Quran',
    hadith: 'Hadith',
    duas: 'Duas',
    adhkar: 'Adhkar',
    dhikr: 'Dhikr',
    habits: 'Habits',
    discover: 'Discover',
    saved: 'Saved',
    progress: 'Progress',
    reminders: 'Reminders',
    settings: 'Settings',
    calendar: 'Calendar',
    books: 'Books',
    home: 'Home',
    explore: 'Explore',
    notes: 'Notes',
    bookmarks: 'Bookmarks',
    analytics: 'Analytics',
    
    // Challenge/Community related
    'join-challenge': 'Join Challenge',
    'other-challenges': 'Other Challenges',
    'daily-charity': 'Daily Charity',
    'complete-quran-ramadan': 'Complete Quran in Ramadan',
    'night-prayer-challenge': 'Night Prayer Challenge',
    'days': 'days',
    
    // Calendar and Events
    'hijri-calendar': 'Hijri Calendar',
    'upcoming-events': 'Upcoming Events',
    'islamic-new-year': 'Islamic New Year',
    'day-of-ashura': 'Day of Ashura',
    'blessed-event-approaching': 'The blessed event is approaching soon',
    'dhul-hijjah': 'Dhul Hijjah',
    'saturday': 'Saturday',
    'gregorian': 'Gregorian',
    
    // Spiritual Wellness
    'spiritual-wellness-tracker': 'Spiritual Wellness Tracker',
    'how-spiritual-state-today': 'How is your spiritual state today?',
    'good': 'Good',
    
    // Progress Analytics
    'progress-analytics': 'Progress Analytics',
    'weekly-activity': 'Weekly Activity',
    'activity-distribution': 'Activity Distribution',
    'recent-achievements': 'Recent Achievements',
    'week': 'week',
    'month': 'month',
    'year': 'year',
    'minutes-read': 'Minutes Read',
    'surahs-read': 'Surahs Read',
    'dhikr-count': 'Dhikr Count',
    'reading-min': 'Reading (min)',
    'keep-up-consistency': 'Keep up the consistency',
    'chapter-complete': 'Chapter Complete',
    'finished-al-fatihah': 'Finished Al-Fatihah',
    'daily-goal-met': 'Daily Goal Met',
    '100-dhikr-today': '100+ dhikr today',
    '7-day-streak': '7-Day Streak!',
    
    // Main Header
    'app-name': 'Deen Companion',
    'search-all': 'Search All',
    
    // Common
    save: 'Save',
    cancel: 'Cancel',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    search: 'Search',
    loading: 'Loading...',
    complete: 'Complete',
    incomplete: 'Incomplete',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    done: 'Done',
    continue: 'Continue',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    close: 'Close',
    view: 'View',
    all: 'All',
    of: 'of',
    for: 'for',
    translation: 'Translation',
    transliteration: 'Transliteration',
    reference: 'Reference',
    error: 'Error',
    'show-less': 'Show less',
    'show-translation': 'Show translation',
    'click-to-copy': 'Click to copy',
    travel: 'Travel',
    protection: 'Protection',
    
    // Prayer Time Tracker
    'prayer-time-tracker': 'Prayer Time Tracker',
    'todays-prayers': "Today's Prayers",
    'prayers-remaining': 'prayers remaining',
    'mark-complete': 'Mark Complete',
    
    // Daily Islamic Goals
    'daily-islamic-goals': 'Daily Islamic Goals',
    'progress-colon': 'Progress:',
    'complete-5-daily-prayers': 'Complete 5 Daily Prayers',
    'perform-obligatory-prayers': 'Perform all obligatory prayers on time',
    'read-1-page-of-quran': 'Read 1 Page of Quran',
    'daily-quran-recitation': 'Daily Quran recitation',
    'morning-evening-adhkar': 'Morning & Evening Adhkar',
    'recite-morning-evening': 'Recite morning and evening remembrance',
    'give-charity-sadaqah': 'Give Charity (Sadaqah)',
    'any-form-charity': 'Any form of charity, even a smile',
    'seek-forgiveness-istighfar': 'Seek Forgiveness (Istighfar)',
    'say-astaghfirullah-100-times': 'Say "Astaghfirullah" 100 times',
    'all-goals-completed': 'All goals completed!',
    'may-allah-accept-efforts': 'May Allah accept your efforts',
    'add-custom-goal': 'Add Custom Goal',
    
    // Personal Dashboard
    'good-morning': 'Good Morning',
    'good-afternoon': 'Good Afternoon',
    'good-evening': 'Good Evening',
    'continue-spiritual-journey': 'Continue your spiritual journey',
    'day-streak': 'Day Streak',
    'total-dhikr': 'Total Dhikr',
    'sessions': 'Sessions',
    'goals-met': 'Goals Met',
    'todays-goals': "Today's Goals",
    'morning-prayers': 'Morning Prayers',
    '100-dhikr': '100 Dhikr',
    '15-min-reading': '15 min Reading',
    'evening-prayers': 'Evening Prayers',
    'weekly-progress': 'Weekly Progress',
    'great-progress-week': 'Great progress this week! You\'re on track to meet your spiritual goals.',
    'recent-activity': 'Recent Activity',
    'last-activity': 'Last activity:',
    'hours-ago': '2 hours ago',
    'read-surah-al-fatihah': 'Read Surah Al-Fatihah',
    
    // Daily Progress
    'daily-progress': 'Daily Progress',
    'tasks-completed': 'tasks completed',
    'task-completed': 'Task Completed! ✅',
    'marked-as-complete': 'marked as complete',
    'all-tasks-completed': 'All Tasks Completed! 🎉',
    'mashallah-completed-tasks': 'Mashallah! You\'ve completed all daily tasks.',
    'progress-reset': 'Progress Reset',
    'daily-progress-reset': 'Daily progress has been reset',
    'reset-todays-progress': 'Reset Today\'s Progress',
    'morning-dua': 'Morning Dua',
    'recite-morning-supplications': 'Recite morning supplications',
    'quran-reading': 'Quran Reading',
    'read-one-page-quran': 'Read at least one page of Quran',
    'dhikr-100x': 'Dhikr 100x',
    'complete-100-dhikr': 'Complete 100 dhikr counts',
    'evening-dua': 'Evening Dua',
    'recite-evening-supplications': 'Recite evening supplications',
    'istighfar': 'Istighfar',
    'seek-forgiveness-33-times': 'Seek forgiveness 33 times',
    
    // Settings
    'customize-journey': 'Customize your spiritual journey',
    location: 'Location',
    'current-location': 'Current Location',
    'update-location': 'Update Location',
    notifications: 'Notifications',
    'prayer-notifications': 'Prayer Notifications',
    'prayer-notifications-desc': 'Get notified for prayer times',
    'adhan-sound': 'Adhan Sound',
    'adhan-sound-desc': 'Play Adhan for prayer times',
    'general-notifications': 'General Notifications',
    'general-notifications-desc': 'App updates and reminders',
    appearance: 'Appearance',
    'dark-mode': 'Dark Mode',
    'dark-mode-desc': 'Toggle dark theme',
    language: 'Language',
    'language-desc': 'Change app language',
    'about-app': 'About Deen Companion',
    version: 'Version',
    'app-description': 'Your companion for Islamic practices and spiritual growth',
    
    // Languages
    arabic: 'العربية',
    english: 'English',
    
    // Prayer times
    fajr: 'Fajr',
    dhuhr: 'Dhuhr',
    asr: 'Asr',
    maghrib: 'Maghrib',
    isha: 'Isha',
    
    // Islamic content
    'islamic-quote-day': 'Islamic Quote of the Day',
    points: 'points',
    'complete-daily-prayers': 'Complete 5 Daily Prayers',
    'read-page-quran': 'Read 1 Page of Quran',
    
    // Dream Journal
    'islamic-dream-journal': 'Islamic Dream Journal',
    'add-dream': 'Add Dream',
    'describe-dream': 'Describe your dream:',
    'dream-placeholder': 'I dreamed that...',
    'save-dream': 'Save Dream',
    'islamic-perspective': 'Islamic Perspective on Dreams',
    'dream-guidance': 'The Prophet (PBUH) said: "Good dreams are from Allah, and bad dreams are from Satan." Record your dreams and seek their interpretation through Islamic knowledge.',
    'dream-added': 'Dream Added',
    'dream-recorded': 'Your dream has been recorded in your journal.',
    dream: 'Dream:',
    reflection: 'Reflection:',
    'no-dreams': 'No dreams recorded yet. Start your spiritual dream journal!',
    'sample-dream-mosque-light': 'I saw myself praying in a beautiful mosque with golden light',
    'sample-dream-interpretation': 'This could signify spiritual growth and divine guidance. Light in dreams often represents knowledge and righteousness.',
    'reflect-dream-islamic-teachings': 'Reflect on this dream in light of Islamic teachings. Consider seeking guidance from knowledgeable sources.',
    personal: 'personal',
    light: 'light',
    mosque: 'mosque',
    prayer: 'prayer',
    positive: 'positive',
    negative: 'negative',
    neutral: 'neutral',
    
    // Charity Tracker
    'charity-impact-tracker': 'Charity Impact Tracker',
    'record-donation': 'Record New Donation',
    'amount': 'Amount ($)',
    'cause-purpose': 'Cause/Purpose',
    'record-donation-btn': 'Record Donation',
    'monthly-goal': 'Monthly Goal',
    'goal-achieved': '🎉 Goal achieved! May Allah reward you.',
    'remaining-goal': '% remaining to reach your goal',
    'people-helped': 'People Helped',
    'acts-kindness': 'Acts of Kindness',
    'this-month': 'This Month',
    'total-donated': 'Total Donated',
    'recent-donations': 'Recent Donations',
    'charity-quote': '"The believer\'s shade on the Day of Resurrection will be his charity." - Prophet Muhammad (PBUH)',
    'donation-recorded': 'Donation Recorded! 🌟',
    'food-for-orphans': 'Food for Orphans',
    'local-islamic-center': 'Local Islamic Center',
    'water-wells': 'Water Wells',
    'islamic-relief': 'Islamic Relief',
    'personal-charity': 'Personal Charity',
    'has-been-added-charity-tracker': 'has been added to your charity tracker',
    
    // Quranic Word Learning
    'quranic-word-learning': 'Quranic Word Learning',
    words: 'words',
    'reveal-meaning': 'Reveal Meaning',
    'mark-learned': 'Mark as Learned',
    learned: '✅ Learned',
    remaining: 'Remaining',
    'word-learned': 'Word Learned! 🎉',
    example: 'Example:',
    'lord-master-sustainer': 'Lord, Master, Sustainer',
    'lord-of-all-worlds': 'Lord of all worlds',
    'most-gracious': 'The Most Gracious',
    'most-gracious-merciful': 'The Most Gracious, Most Merciful',
    'establish-prayer': 'Establish prayer',
    'obligatory-charity': 'Obligatory charity',
    'give-zakah': 'Give zakah',
    praise: 'Praise',
    'praise-be-allah': 'Praise be to Allah',
    'youve-learned': "You've learned",
    
    // Spiritual Journal
    'spiritual-journal': 'Spiritual Journal',
    'new-entry': 'New Entry',
    'search-journal': 'Search your journal...',
    'todays-reflection-prompt': 'Today\'s Reflection Prompt',
    'entry-title': 'Entry title...',
    'write-reflections': 'Write your spiritual reflections here...',
    'mood': 'Mood',
    'tags': 'Tags',
    'add-tag': 'Add tag...',
    'save-entry': 'Save Entry',
    'no-journal-entries': 'No journal entries yet',
    'start-spiritual-journaling': 'Start your spiritual journaling journey!',
    'incomplete-entry': 'Incomplete Entry',
    'add-title-content': 'Please add both a title and content to your journal entry.',
    'entry-saved': 'Entry Saved',
    'reflection-saved': 'Your spiritual reflection has been saved to your journal.',
    'grateful': 'Grateful',
    'peaceful': 'Peaceful',
    'hopeful': 'Hopeful',
    'reflective': 'Reflective',
    'seeking': 'Seeking Guidance',
    'current-prompt': 'Current Prompt:',
    
    // Habit Builder
    'islamic-habit-builder': 'Islamic Habit Builder',
    'overall-level': 'Overall Level',
    'habits-completed-today': 'habits completed today',
    'habit-completed': 'Habit Completed!',
    'streak-days': 'days',
    'level-up': 'Level Up!',
    'reached-level': 'reached level',
    'add-new-islamic-habit': 'Add New Islamic Habit',
    'most-beloved-deeds': '"The most beloved of deeds to Allah are those that are most consistent, even if they are small." - Prophet Muhammad (PBUH)',
    'recent-achievement': 'Recent Achievement',
    'consistent-reader': 'Consistent Reader - Read Quran for 10 days straight!',
    'morning-adhkar': 'Morning Adhkar',
    'recite-morning-remembrance': 'Recite morning remembrance of Allah',
    'read-quran': 'Read Quran',
    'read-one-page-daily': 'Read at least one page of Quran daily',
    'make-dua-parents': 'Make Dua for Parents',
    'remember-parents-prayers': 'Remember parents in daily prayers',
    worship: 'worship',
    knowledge: 'knowledge',
    character: 'character',
    health: 'health',
    
    // Surah translations and names
    'quran-karim': 'Holy Quran',
    'popular-surahs': 'Popular Surahs',
    'the-opening': 'The Opening',
    'the-sincerity': 'The Sincerity',
    'the-daybreak': 'The Daybreak',
    mankind: 'Mankind',
    'the-cow': 'The Cow',
    'the-cave': 'The Cave',
    'the-beneficent': 'The Beneficent',
    'the-sovereignty': 'The Sovereignty',
    surah: 'Surah',
    'back-to-surahs': 'Back to Surahs',
    'toggle-translation': 'Toggle Translation',
    'verse-copied-clipboard': 'Verse copied to clipboard',
    'full-surah-copied-clipboard': 'Full Surah copied to clipboard',
    'recently-read': 'Recently read',
    
    // Duas Section
    'daily-duas': 'Daily Duas',
    'daily-duas-supplications': 'Daily Duas (Supplications)',
    'search-duas-placeholder': 'Search duas, transliteration, or translation...',
    'morning-dua-translation': 'We have reached the morning and at this very time unto Allah belongs all sovereignty, and all praise is for Allah.',
    'evening-dua-translation': 'We have reached the evening and at this very time unto Allah belongs all sovereignty, and all praise is for Allah.',
    'food-drink': 'Food & Drink',
    'before-eating': 'Before Eating',
    'after-eating': 'After Eating',
    'before-eating-translation': 'In the name of Allah.',
    'after-eating-translation': 'All praise is due to Allah who has fed me this food and provided it for me without any might or power on my part.',
    'when-starting-journey': 'When Starting Journey',
    'travel-dua-translation': 'Glory unto Him Who created this transportation for us though we were unable to create it on our own. And unto our Lord we shall return.',
    'ayat-kursi': 'Ayat al-Kursi',
    'ayat-kursi-translation': 'Allah - there is no deity except Him, the Ever-Living, the Sustainer of existence.',
    'copy-arabic-text': 'Copy Arabic text',
    'no-duas-found': 'No duas found matching your search.',
    
    // Bookmarks
    'added-to-bookmarks': 'Added to bookmarks',
    'removed-from-bookmarks': 'Removed from bookmarks',
    'already-bookmarked': 'Already bookmarked',
    'item-already-bookmarked': 'This item is already in your bookmarks.',
    'item-saved-bookmarks': '{title} has been saved to your bookmarks.',
    'dua-saved-bookmarks': '{title} has been saved to your bookmarks.',
    'dua-removed-bookmarks': '{title} has been removed from your bookmarks.',
    'dua-arabic-copied': '{title} Arabic text copied',
    
    // Toast messages
    'surah-loaded': 'Surah Loaded',
    'surah-ready-reading': 'Surah {name} is ready for reading.',
    'failed-load-surah': 'Failed to load the Surah. Please try again.',
    'found-result': 'Found Result',
    'navigated-to': 'Navigated to {title}',
    
    // Quran verse translations
    'bismillah-translation': 'In the name of Allah, the Entirely Merciful, the Especially Merciful.',
    'alhamdulillah-translation': 'All praise is due to Allah, Lord of the worlds -',
    'rahman-rahim-translation': 'The Entirely Merciful, the Especially Merciful,',
    'malik-yawm-translation': 'Sovereign of the Day of Recompense.',
    'iyyaka-nabudu-translation': 'It is You we worship and You we ask for help.',
    'ihdina-sirat-translation': 'Guide us to the straight path -',
    'sirat-alladhina-translation': 'The path of those upon whom You have bestowed favor, not of those who have evoked Your anger or of those who are astray.',
    'qul-huwa-allah-translation': 'Say, "He is Allah, [who is] One,',
    'allah-samad-translation': 'Allah, the Eternal Refuge.',
    'lam-yalid-translation': 'He neither begets nor is born,',
    'walam-yakun-translation': 'Nor is there to Him any equivalent."',
    'qul-auzu-birabb-falaq': 'Say, "I seek refuge in the Lord of daybreak',
    'min-sharri-ma-khalaq': 'From the evil of that which He created',
    'min-sharri-ghasiq': 'And from the evil of darkness when it settles',
    'min-sharri-naffathat': 'And from the evil of the blowers in knots',
    'min-sharri-hasid': 'And from the evil of an envier when he envies."',
    'qul-auzu-birabb-nas': 'Say, "I seek refuge in the Lord of mankind,',
    'maliki-nas': 'The Sovereign of mankind.',
    'ilahi-nas': 'The God of mankind,',
    'min-sharri-waswas': 'From the evil of the retreating whisperer -',
    'alladhi-yuwaswis': 'Who whispers [evil] into the breasts of mankind -',
    'min-jinnati-wanas': 'From among the jinn and mankind."',
    
    // Bottom navigation
    'quran-tab': 'Quran',
    'explore-tab': 'Explore',
    'home-tab': 'Home',
    'duas-tab': 'Duas',
    'notes-tab': 'Notes',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ar'); // Arabic as default

  useEffect(() => {
    // Apply RTL/LTR to document
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string, params?: Record<string, any>): string => {
    let translation = translations[language][key] || key;
    
    // Simple parameter replacement
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{${param}}`, params[param]);
      });
    }
    
    return translation;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
